import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import favIcon from '../../public/assets/logo1.png'
import './globals.css'
import Image from 'next/image'

const roboto = Roboto({ 
  weight: ['400', '500', '700'],
  subsets: ['latin'] 
})


export const metadata: Metadata = {
  title: 'Portifólio',
  description: 'Generated by create next app',
  // icons: {
  //   icon: '/favicon.ico',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="62x62"/>
      </head>
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
